#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
PRIMARY_ROOT = ROOT / "public" / "block-icons" / "primary"
UNUSED_ROOT = ROOT / "public" / "block-icons" / "unused"
PACKED_ROOT = ROOT / "public" / "block-icons" / "packed"
MANIFEST_TS = ROOT / "src" / "data" / "blockIconAtlases.ts"
ATLAS_CELL_SIZE = 16

try:
    RESAMPLE_NEAREST = Image.Resampling.NEAREST
except AttributeError:
    RESAMPLE_NEAREST = Image.NEAREST


def fit_icon_to_cell(image: Image.Image, cell_size: int) -> Image.Image:
    if image.width == cell_size and image.height == cell_size:
        return image.copy()

    scale = min(cell_size / image.width, cell_size / image.height)
    width = max(1, round(image.width * scale))
    height = max(1, round(image.height * scale))
    resized = image.resize((width, height), RESAMPLE_NEAREST)
    fitted = Image.new("RGBA", (cell_size, cell_size), (0, 0, 0, 0))
    offset_x = (cell_size - width) // 2
    offset_y = (cell_size - height) // 2
    fitted.alpha_composite(resized, (offset_x, offset_y))
    return fitted


def build_atlas(name: str, source_dir: Path) -> dict:
    icons = sorted(path for path in source_dir.glob("*.png"))
    if not icons:
        raise RuntimeError(f"No icons found in {source_dir}")

    opened = [(icon, Image.open(icon).convert("RGBA")) for icon in icons]
    try:
        cell_size = ATLAS_CELL_SIZE
        columns = max(1, math.ceil(math.sqrt(len(opened))))
        rows = math.ceil(len(opened) / columns)
        atlas = Image.new("RGBA", (columns * cell_size, rows * cell_size), (0, 0, 0, 0))

        entries: dict[str, int] = {}
        for index, (icon_path, image) in enumerate(opened):
            x = (index % columns) * cell_size
            y = (index // columns) * cell_size
            atlas.alpha_composite(fit_icon_to_cell(image, cell_size), (x, y))
            entries[icon_path.stem] = index

        hasher = hashlib.sha256()
        hasher.update(json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8"))
        hasher.update(atlas.tobytes())
        digest = hasher.hexdigest()[:12]
        out_name = f"{name}.{digest}.png"
        out_path = PACKED_ROOT / out_name
        atlas.save(out_path, optimize=True)
    finally:
        for _, image in opened:
            image.close()

    return {
        "src": f"block-icons/packed/{out_name}",
        "cellSize": cell_size,
        "columns": columns,
        "rows": rows,
        "width": columns * cell_size,
        "height": rows * cell_size,
        "entries": entries,
    }


def write_manifest(manifests: dict[str, dict]) -> None:
    content = """/**
 * Public API:
 * - BlockIconAtlasName
 * - BlockIconAtlasManifest
 * - BLOCK_ICON_ATLASES
 *
 * Callers:
 * - src/lib/blockIconAtlas.ts
 *
 * Generated by scripts/build-icon-atlases.py. Do not edit manually.
 */
// Callers:
// - src/lib/blockIconAtlas.ts
export type BlockIconAtlasName = "primary" | "unused";

// Callers:
// - src/lib/blockIconAtlas.ts
export interface BlockIconAtlasManifest {
  src: string;
  cellSize: number;
  columns: number;
  rows: number;
  width: number;
  height: number;
  entries: Record<string, number>;
}

// Callers:
// - src/lib/blockIconAtlas.ts
export const BLOCK_ICON_ATLASES = """ + json.dumps(manifests, indent=2, sort_keys=True) + """ as const satisfies Record<BlockIconAtlasName, BlockIconAtlasManifest>;
"""
    MANIFEST_TS.write_text(content, encoding="utf-8")


def main() -> int:
    PACKED_ROOT.mkdir(parents=True, exist_ok=True)
    for stale in PACKED_ROOT.glob("*.png"):
        stale.unlink()

    manifests = {
        "primary": build_atlas("primary", PRIMARY_ROOT),
        "unused": build_atlas("unused", UNUSED_ROOT),
    }
    write_manifest(manifests)

    print(f"Packed atlases written to: {PACKED_ROOT.relative_to(ROOT)}")
    print(f"Manifest written to: {MANIFEST_TS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
